name: PR

on: pull_request

jobs:
  integration_tests:
    name: Build and Test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Select Xcode 11.2
        run: sudo xcode-select -s /Applications/Xcode_11.2.app
      - name: Install Bazel
        run: brew install bazelisk buildifier
      - name: Build and Test
        run: bazelisk test //...
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: bazel-testlogs
          path: bazel-testlogs
      - name: buildifier
        run: find . -type f \( -name 'WORKSPACE' -o -name '*.bzl' -o -name '*.bazel' \) | xargs buildifier --mode=diff
      - name: Check docs
        run: bazelisk run docs --nocheck_visibility && git diff --exit-code docs
